<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Verifikasi</name>
   <tag></tag>
   <elementGuidId>3debb239-0f8f-43a8-aa20-179683eb0cf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div > div > button.bl-button.bl-button--primary.bl-button--medium.bl-button--block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='TFAJS-1652931414636']/section/div/div[2]/div/div[2]/div/div/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aa1a4d44-707b-438c-b710-d001a7fb62ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bl-button bl-button--primary bl-button--medium bl-button--block</value>
      <webElementGuid>a0bef88a-58be-4ab1-b5e4-2183b92c2994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Verifikasi </value>
      <webElementGuid>d0d0d34b-89c6-436d-97e0-f54c691cc2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TFAJS-1652931414636&quot;)/section[1]/div[@class=&quot;bl-modal p-24&quot;]/div[@class=&quot;bl-modal__wrapper&quot;]/div[@class=&quot;bl-card&quot;]/div[@class=&quot;bl-modal__body&quot;]/div[@class=&quot;p-24&quot;]/div[1]/div[1]/div[1]/button[@class=&quot;bl-button bl-button--primary bl-button--medium bl-button--block&quot;]</value>
      <webElementGuid>0b1f4c66-dcc9-4ac6-9ed0-5372baf1197e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TFAJS-1652931414636']/section/div/div[2]/div/div[2]/div/div/div/div/button</value>
      <webElementGuid>55356079-5e50-4e60-9e2c-83a3aeaf15b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tunggu 2 detik'])[1]/following::button[1]</value>
      <webElementGuid>cbc937e3-2490-4147-803d-0dee90ce49c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode rahasia'])[1]/following::button[1]</value>
      <webElementGuid>7ccc22b3-d99c-4bc0-9d2b-c6acee6cd130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button</value>
      <webElementGuid>cc962621-1695-4c39-a209-7b14af803fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Verifikasi ' or . = ' Verifikasi ')]</value>
      <webElementGuid>8bf40299-8f84-4cb5-a84b-2fe9c1ceb29d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
