<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kirim Sekarang</name>
   <tag></tag>
   <elementGuidId>aa2509ea-6ab1-403e-957b-e8690eb4fd74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.unf-btn.unf-btn--animate.unf-btn--filled.unf-btn--primary.unf-btn--large.unf-btn--block.css-1dl5bj6-unf-btn.egehon70</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[11]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a8a82724-7ce0-472d-a299-6c5b2a7f2013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>unf-btn unf-btn--animate unf-btn--filled unf-btn--primary unf-btn--large unf-btn--block css-1dl5bj6-unf-btn egehon70</value>
      <webElementGuid>34198069-9076-401c-a043-c532fe23ba53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unify</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>a73ccd34-b104-4064-b3da-8ca0c40cb82e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f6aff20a-c415-42e5-948a-3b534aaa7b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kirim Sekarang</value>
      <webElementGuid>1a740276-3d5f-4c57-8ff0-d6b3cd0b96c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[6]/div[@class=&quot;css-1tbvo2g-unf-modal e1nc1fa20&quot;]/div[@class=&quot;css-1qwpmq4&quot;]/div[@class=&quot;css-vpkyow&quot;]/div[1]/button[@class=&quot;unf-btn unf-btn--animate unf-btn--filled unf-btn--primary unf-btn--large unf-btn--block css-1dl5bj6-unf-btn egehon70&quot;]</value>
      <webElementGuid>69ae85a0-f192-4a23-bbd8-c6f8be1a6964</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[11]</value>
      <webElementGuid>b1bca50c-771e-45ae-a767-1f2e257dd9ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berikan akses masuk ke akunmu dengan klik notifikasi di aplikasi Tokopedia pada perangkat:'])[1]/following::button[1]</value>
      <webElementGuid>45ee781a-ca3f-4189-9f0a-1fbcb0917cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifikasi lewat notifikasi'])[1]/following::button[1]</value>
      <webElementGuid>ce115334-9772-4c33-9727-23881e58d8e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buka aplikasi Tokopedia agar notifikasi lebih mudah terkirim.'])[1]/preceding::button[1]</value>
      <webElementGuid>c848d7ce-790a-47be-892e-ea5d9e3d2107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/div/button</value>
      <webElementGuid>4b42adcb-b747-41e7-b598-557ef54c7ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Kirim Sekarang' or . = 'Kirim Sekarang')]</value>
      <webElementGuid>d666d259-54b6-40ca-ad6b-0fd021aa05fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
