<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Komputer  Laptop_css-18i7x95-unf-mod_b26b56</name>
   <tag></tag>
   <elementGuidId>fac4b595-c1fb-48bc-a0d9-e01a9244f04f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.css-18i7x95-unf-modal__icon.e1nc1fa21</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[6]/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ce8cb186-8e8b-4d25-b04e-8ad9c37f0d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Tutup tampilan modal</value>
      <webElementGuid>57315d9a-48bf-4e0d-999c-a6cefba53a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>modal-close</value>
      <webElementGuid>0cab9db5-2723-4c70-b8d9-cee7e2f0ac88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-18i7x95-unf-modal__icon e1nc1fa21</value>
      <webElementGuid>7e6c1356-cc1e-416b-8a78-43f5a8f7ae99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[6]/div[@class=&quot;css-1tbvo2g-unf-modal e1nc1fa20&quot;]/button[@class=&quot;css-18i7x95-unf-modal__icon e1nc1fa21&quot;]</value>
      <webElementGuid>d305e267-7080-4613-8d79-cef9d4b4762a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/button</value>
      <webElementGuid>c2463da3-c16b-4880-8876-339483c9d929</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
