<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>317fc05c-c50c-4e22-8314-83aeb30f58d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.slp-btn.navigation-item-top.slp-ml-24.slp-btn-ghost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='be-navigation-desktop']/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2a265552-a66d-4e2b-b598-19bfdb77f002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://gitlab.com/users/sign_in/</value>
      <webElementGuid>dd49c5ce-47e5-4e71-afa1-72bddaff6b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>a7f2f740-c56b-4b5c-bd1a-d4a2e8a439fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nav</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>520ab767-6a7e-488a-8174-b37cac5eb753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slp-btn navigation-item-top slp-ml-24 slp-btn-ghost</value>
      <webElementGuid>13d1ea08-e056-4be1-990d-8e36cad731db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Login </value>
      <webElementGuid>212f13b7-d224-4cab-93c8-6efa66ee07fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;be-navigation-desktop&quot;)/div[@class=&quot;navigation&quot;]/div[@class=&quot;navigation-top&quot;]/a[@class=&quot;slp-btn navigation-item-top slp-ml-24 slp-btn-ghost&quot;]</value>
      <webElementGuid>8abbc4f3-1aaa-49eb-a703-bbb6c41e660b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='be-navigation-desktop']/div/div/a</value>
      <webElementGuid>b5f54e6c-8fbd-4723-a303-eca239384e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>ca3890ff-03fe-4e23-914d-507c4ea41143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Sales'])[1]/following::a[1]</value>
      <webElementGuid>74148667-83fe-4543-972e-5538f4efe37b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set up support services'])[1]/following::a[2]</value>
      <webElementGuid>fec6593e-311d-4f30-8a74-222003e05fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/preceding::a[1]</value>
      <webElementGuid>2aa59d19-035a-400e-ae9d-926b6ab7ea8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/preceding::a[1]</value>
      <webElementGuid>862bed0f-4691-44d4-ae9c-2e9aa4248a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>150b9410-9c0c-43e6-a2e7-7857da3fd966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://gitlab.com/users/sign_in/')]</value>
      <webElementGuid>ada5a3ef-054a-405a-9615-248d8c589235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>ae8f6172-1214-4636-8b19-0facc774bd10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://gitlab.com/users/sign_in/' and @title = 'Login' and (text() = ' Login ' or . = ' Login ')]</value>
      <webElementGuid>d3303bc1-2fc3-4215-8cd7-eff31a3055c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
