<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Kategori_css-w3ze74</name>
   <tag></tag>
   <elementGuidId>88728a83-e7bf-4045-8cbc-f8be70e5d0c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form.css-w3ze74</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@action='/search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>81f54d87-abe4-49a7-b495-d8d939bf224d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-w3ze74</value>
      <webElementGuid>1cb7f354-c6ca-42a1-99c9-01c3861cb8b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>action</name>
      <type>Main</type>
      <value>/search</value>
      <webElementGuid>504c8728-a52a-4991-8465-e343fe85e1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>get</value>
      <webElementGuid>434c43b8-49c8-454f-808b-3f436054066c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-container&quot;)/form[@class=&quot;css-w3ze74&quot;]</value>
      <webElementGuid>a488b5b0-6782-44a3-a5cf-bc218148607c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@action='/search']</value>
      <webElementGuid>99080784-6059-4b87-a501-89ca7ca4151d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-container']/form</value>
      <webElementGuid>780c2b87-c180-4361-8146-63ff40cad002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[1]/following::form[1]</value>
      <webElementGuid>9e51625f-d289-43bf-9cdf-6510486e36fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tokopedia Care'])[1]/following::form[1]</value>
      <webElementGuid>95a84aa6-db05-44e1-8c33-a3f12df94618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/preceding::form[1]</value>
      <webElementGuid>5532b2bc-1a57-455e-abdb-6ce5149429fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>6f2975da-eb95-44f7-8323-50916f315574</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
