<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Authorize gitlabhq</name>
   <tag></tag>
   <elementGuidId>ac509f91-3c35-4545-b7eb-e0269d4ebd4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js-oauth-authorize-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='js-oauth-authorize-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0e42af9b-7cc8-47f4-b458-bf491820c2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-octo-click</name>
      <type>Main</type>
      <value>oauth_application_authorization</value>
      <webElementGuid>58cdb9ad-e639-438d-bd41-d0d99b443ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-octo-dimensions</name>
      <type>Main</type>
      <value>marketplace_listing_id:,came_from_marketplace:false,paid_marketplace_plan_purchased:false</value>
      <webElementGuid>f0515084-2b54-4c56-9fff-dfcc303b5d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ga-click</name>
      <type>Main</type>
      <value>Oauth, oauth application authorized, oauth_application_id:62872; listing_id:; came_from_integrations_directory:false; came_from_marketplace:false; paid_marketplace_plan_purchased:false; marketplace_listing_id:</value>
      <webElementGuid>d3570442-7297-403a-aea2-298ece8e2dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>720a0c46-a642-49ae-b71c-6149c54c00f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>authorize</value>
      <webElementGuid>89ebc1a2-59cd-4628-bf22-567485471bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d95d7c9e-d92c-4e73-ace5-bc0e6e9dd424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js-oauth-authorize-btn</value>
      <webElementGuid>5d804a21-e177-46c7-b38b-93a80ea6ffc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary width-full ws-normal</value>
      <webElementGuid>1202f112-8604-4fd8-a7c6-215491ef587d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Authorize gitlabhq</value>
      <webElementGuid>d0e70965-a895-4b7d-848d-1380c4d3215d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-oauth-authorize-btn&quot;)</value>
      <webElementGuid>b76d06e8-1b32-47ed-a1cb-0582b4902ab6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='js-oauth-authorize-btn']</value>
      <webElementGuid>d170bb87-cbf6-4764-9a78-d4393f257de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='js-pjax-container']/div/div[2]/div/div[2]/div/form/div/button[2]</value>
      <webElementGuid>f5fea5ba-101a-42d7-a263-8ff74f11d75a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>231fa39e-bd66-4d7d-8fa5-0f8a47005a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/following::button[2]</value>
      <webElementGuid>c1a1c453-6b85-4508-a1fe-b44813b1c46c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://gitlab.com'])[1]/preceding::button[1]</value>
      <webElementGuid>6f2d6480-c2a4-4468-b959-5c63a7724185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Authorize gitlabhq']/parent::*</value>
      <webElementGuid>7d516277-541f-45c7-9c13-857642d1d708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>2b78f6db-1c67-4629-ad5b-c6128dc37af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'authorize' and @id = 'js-oauth-authorize-btn' and (text() = 'Authorize gitlabhq' or . = 'Authorize gitlabhq')]</value>
      <webElementGuid>31b29105-6f81-4556-8c19-74ae05ee365b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
