<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lanjutkan</name>
   <tag></tag>
   <elementGuidId>55c8f4d7-d427-441a-9774-ca44cef25b38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.submit-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>306d1c9d-f4f6-4404-901c-c66f3a4c5dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8ceeacff-6928-4a08-9d9c-fb7edce49b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit-button</value>
      <webElementGuid>d7ee4bef-e42d-4ca8-b61f-5223a855c018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Lanjutkan </value>
      <webElementGuid>3aefd3be-f409-41bc-b64d-005310b42129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;landing-page-container&quot;]/div[@class=&quot;master-container&quot;]/div[@class=&quot;master-container-inner&quot;]/div[@class=&quot;sign-in-container&quot;]/div[@class=&quot;signin-modal-wrapper&quot;]/div[1]/div[@class=&quot;login-modal showLogin&quot;]/div[@class=&quot;generic-modal&quot;]/div[@class=&quot;modal-base showModal slide-up&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;modal-content-data&quot;]/div[@class=&quot;pnl-manager&quot;]/div[@class=&quot;otp-container&quot;]/button[@class=&quot;submit-button&quot;]</value>
      <webElementGuid>227bdbe3-f408-4c8f-9076-5a1dbad4c956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6c4b84f3-51d4-4532-b437-83bf56fdd9dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>82c37517-3f83-427b-9076-439a45d8ff46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit-button</value>
      <webElementGuid>519738e2-bed8-46d8-a01e-b963cd0321b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Lanjutkan </value>
      <webElementGuid>891859e8-2d44-4eec-ab2d-1b5da973a55b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;landing-page-container&quot;]/div[@class=&quot;master-container&quot;]/div[@class=&quot;master-container-inner&quot;]/div[@class=&quot;sign-in-container&quot;]/div[@class=&quot;signin-modal-wrapper&quot;]/div[1]/div[@class=&quot;login-modal showLogin&quot;]/div[@class=&quot;generic-modal&quot;]/div[@class=&quot;modal-base showModal slide-up&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;modal-content-data&quot;]/div[@class=&quot;pnl-manager&quot;]/div[@class=&quot;otp-container&quot;]/button[@class=&quot;submit-button&quot;]</value>
      <webElementGuid>51dd1e34-b267-4f7a-998a-3ce75a093c6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>10ca76be-7a67-483c-ba01-3e658fa25033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[3]/div/div/div/div/div[2]/div/div/div/div/button</value>
      <webElementGuid>d39417be-196c-4683-8aa3-7520136d3e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dapatkan kode melalui panggilan'])[1]/following::button[1]</value>
      <webElementGuid>087f5711-7562-4633-a81d-c2ca755156dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak menerima SMS?'])[1]/following::button[2]</value>
      <webElementGuid>5f2e7b35-3dc5-4561-9c6b-8bd17e3f1f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang Disney+ Hotstar'])[1]/preceding::button[1]</value>
      <webElementGuid>27ecfcfc-dc19-4cac-aecc-ef8e1a2be9fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button</value>
      <webElementGuid>d059b0b8-eb14-468e-b43f-88a547b65f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Lanjutkan ' or . = ' Lanjutkan ')]</value>
      <webElementGuid>0b4dce08-bb49-4811-9f94-40d8db73dd68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
