<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Masuk</name>
   <tag></tag>
   <elementGuidId>0a2d2bd9-4bc8-4872-b458-3acf5ccdb98c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.signIn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div/div/div[2]/div/div[6]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3942e351-d4a4-49d0-8c87-db1dedc7f417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>d0e80eec-a48f-4dcd-93ba-10fa9b99b96b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>signIn</value>
      <webElementGuid>0d8ab0d1-69b3-40ff-9571-c2dff99346e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>0c17415d-3016-42f6-82ba-dc76c143ff92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;landing-page-container&quot;]/div[@class=&quot;master-container&quot;]/div[@class=&quot;master-container-inner&quot;]/div[@class=&quot;header-container&quot;]/div[@class=&quot;static-container&quot;]/div[@class=&quot;header fixed-header with-subs-nudge&quot;]/div[@class=&quot;nav-container&quot;]/div[@class=&quot;right-element user-profile&quot;]/div[@class=&quot;signIn&quot;]</value>
      <webElementGuid>052e4aec-12d6-4613-b3bc-faa9196d1808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5de03b2c-96a9-4593-b4ca-0ac5ec5e1fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>758ccc39-9a08-4c06-923b-c74a37755133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>signIn</value>
      <webElementGuid>36123027-6cf3-46fa-b0f8-211c4d742cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>2431c0b1-fb9a-4a81-9b3d-832a5f4fc2d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;landing-page-container&quot;]/div[@class=&quot;master-container&quot;]/div[@class=&quot;master-container-inner&quot;]/div[@class=&quot;header-container&quot;]/div[@class=&quot;static-container&quot;]/div[@class=&quot;header fixed-header with-subs-nudge&quot;]/div[@class=&quot;nav-container&quot;]/div[@class=&quot;right-element user-profile&quot;]/div[@class=&quot;signIn&quot;]</value>
      <webElementGuid>ce8c00d1-71ba-40d6-ae9e-f84aec70726f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/div[2]/div/div[6]/div</value>
      <webElementGuid>f7b37f94-daf5-40df-8bcd-df6f7eb2fdbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesian'])[1]/following::div[3]</value>
      <webElementGuid>aaaddfcb-e498-4541-8580-40a2f19ff801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Langganan'])[1]/following::div[6]</value>
      <webElementGuid>5be78eea-40a4-4fc0-a428-b308cba22357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WandaVision'])[1]/preceding::div[8]</value>
      <webElementGuid>80da43be-a178-400e-84f8-31bea1908507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masuk']/parent::*</value>
      <webElementGuid>b2dbe874-2704-4ce0-948a-c4018545ab90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
      <webElementGuid>8f51b7df-3586-4d92-9a15-8d73cd9e404e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>4a76eafc-d931-484c-8fb8-49212dfc27d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
