<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Kategori_css-w3ze74</name>
   <tag></tag>
   <elementGuidId>00ec7c0b-c0f2-4f13-80e1-8ba1142fd92e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form.css-w3ze74</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@action='/search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>a2e57958-0b5e-4b1e-bedb-62f7630eb95e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-w3ze74</value>
      <webElementGuid>5d4f8960-6ddc-48d8-9494-205c098ea30c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>action</name>
      <type>Main</type>
      <value>/search</value>
      <webElementGuid>6760c9f0-a93d-496f-8232-cf9ec51ed3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>get</value>
      <webElementGuid>527a1f72-9386-4a2b-ae0c-b3685b14564d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-container&quot;)/form[@class=&quot;css-w3ze74&quot;]</value>
      <webElementGuid>08f6bb0d-6504-418c-8703-7492cce27290</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@action='/search']</value>
      <webElementGuid>9c008b62-57f6-4e68-bac7-24f5174b7046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-container']/form</value>
      <webElementGuid>337251ea-c2a1-4048-87fa-a16481fde0df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[1]/following::form[1]</value>
      <webElementGuid>05b1123d-a53f-4908-8ae3-7dae86f80763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tokopedia Care'])[1]/following::form[1]</value>
      <webElementGuid>87ad7149-f02a-4052-a5dc-f5a234292f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/preceding::form[1]</value>
      <webElementGuid>332fc41d-d12f-438e-9411-51cb55e84734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>d1fa542b-2355-4a2a-99c5-439936b507f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
