<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Persyaratan_VmOpGe</name>
   <tag></tag>
   <elementGuidId>c2752d77-1882-4170-8b34-4293aa740d8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.VmOpGe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='yDmH0d']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3af3ec79-f9b0-44b6-8b6f-e0f50b92522b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>VmOpGe</value>
      <webElementGuid>bbf327be-d08b-463b-bec6-9c20502a8807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c7aa52bb-dc8f-42ab-8d11-f30141937846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yDmH0d&quot;)/div[@class=&quot;H2SoFe LZgQXe RELBvb TFhTPc&quot;]/div[@class=&quot;VmOpGe&quot;]</value>
      <webElementGuid>f86a7598-31aa-4ba7-95f1-82d794cbc6dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='yDmH0d']/div/div[2]</value>
      <webElementGuid>50113377-24b5-49cb-88d0-51c6f508e442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>571871f4-c30d-491d-9a39-84d2e8b232af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
